#!/bin/bash
echo "=== PERFORMANCE COUNTER ANALYSIS ==="
echo ""
echo "Pattern         Cycles    IPC    Branch-Miss  Cache-Miss  L1-Miss"
echo "-----------------------------------------------------------------------"
echo "a*_16 (5.46x)   8.8M      2.84   1.31% ❌     18.65% ❌❌  0.20%"
echo "a*_256 (34.8x)  14.5M     3.81   0.53% ✅     12.03% ✅   0.08% ✅"
echo "[a-z]*_32 (5.2x) 11.4M    3.06   1.06% ❌     17.10% ❌❌  0.28%"
echo ""
echo "🔍 KEY FINDINGS:"
echo ""
echo "1. SHORT PATTERNS HAVE 50% MORE CACHE MISSES!"
echo "   - a*_16: 18.65% cache miss rate"
echo "   - [a-z]*_32: 17.10% cache miss rate"
echo "   - a*_256: 12.03% cache miss rate ✅"
echo ""
echo "2. SHORT PATTERNS HAVE 2.5x MORE BRANCH MISSES!"
echo "   - Short: ~1.0-1.3% branch miss"
echo "   - Long: ~0.5% branch miss"
echo ""
echo "3. IPC IS LOWER FOR SHORT PATTERNS"
echo "   - a*_16: 2.84 IPC (CPU waiting!)"
echo "   - a*_256: 3.81 IPC (CPU busy!)"
echo ""
echo "🎯 ROOT CAUSE: I-CACHE THRASHING + BRANCH MISPREDICTION"
echo ""
echo "Short patterns:"
echo "  - Execute more loop iterations per byte processed"
echo "  - More branches = more mispredictions"
echo "  - More function calls = worse I-cache locality"
echo ""
echo "Solution ideas:"
echo "  1. Inline functions aggressively for short paths"
echo "  2. Reduce branching in 16-byte path"
echo "  3. Optimize cold branch layout"
