#!/bin/bash
echo "=== ANALYZING 32-BYTE REGRESSION ==="
echo ""
echo "Baseline (before 64-byte unroll):"
echo "  a*_32:     5.98x"
echo "  [a-z]*_32: 6.03x"
echo ""
echo "Current (after 64-byte unroll):"
echo "  a*_32:     5.10-5.15x  (❌ -14%)"
echo "  a+_32:     8.76x       (✅ +3%)"
echo "  [a-z]*_32: 5.11x       (❌ -15%)"
echo ""
echo "🔍 HYPOTHESIS:"
echo "The 64-byte unroll added extra conditional checks that slow down"
echo "the 32-byte path even though it doesn't execute the 64-byte loop."
echo ""
echo "💡 FIX STRATEGY:"
echo "Option A: Skip 64-byte check for inputs < 64 bytes (compile-time)"
echo "Option B: Optimize the conditional logic"
echo "Option C: Fast path for exact 32-byte inputs"
echo ""
echo "Let's try Option B first - optimize the conditions..."
