#!/bin/bash
echo "=== UNDERPERFORMER ANALYSIS ==="
echo ""
echo "🔴 CRITICAL (< 4x - need optimization):"
echo "  1. a*_16:      3.65x  (16-byte SIMD overhead)"
echo "  2. suffix_ing: 2.62x  (complex pattern [a-zA-Z]+ing)"
echo ""
echo "🟡 GOOD BUT CAN IMPROVE (4-6x):"
echo "  3. a+_16:      4.16x  (16-byte plus pattern)"
echo "  4. a*_32:      5.12x  (star 12% slower than plus)"
echo "  5. [a-z]*_32:  5.09x  (range star pattern)"
echo ""
echo "🎯 OPTIMIZATION TARGETS:"
echo ""
echo "Target #1: 16-byte patterns (overhead dominates)"
echo "  - Current: 3.65x for a*_16"
echo "  - Goal: 5x+ (reduce dispatch overhead)"
echo ""
echo "Target #2: Star vs Plus gap"
echo "  - Current: * is 12% slower than +"
echo "  - Goal: Make them equal (both ~2ns)"
echo ""
echo "Target #3: Complex patterns"
echo "  - suffix_ing: 2.62x"
echo "  - These need different approach (not pure SIMD)"
